name: PushToServer

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  push_server:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: maulanar.my.id
          user: maulana
          key: ${{secrets.PUBLICKEY}}
          command: |
            export PATH=$PATH:/usr/local/go/bin
            cd /home/maulana/auto_typer
            git pull origin master
